INHERIT: ./mkdocs_base.yml

site_name: サンプルドキュメント
# site_description: sasano8's portfolio
site_url: https://portfolio.ys-method.com/
# repo_name: encode/httpx
repo_url: https://github.com/sasano8/portfolio/
edit_uri: "edit/main/docs/"

# plugins:
#   - with-pdf:
#       cover: true
#       cover_title: Sample Document

nav:
  - はじめに: "index.md"
